<?php
namespace www\examplenamespace\cl\service;
// file:ExampleHelloService.php
/**
 * @generated The structure of this class is generated by CloudKing
 * Class ExampleHelloService
 */
class ExampleHelloService implements IExampleHelloService {

	/**
	 * @inheritDoc
	 */
	public function hello(&$param) {
		return $param.' world';
	}
} // end class 
 