<?php
namespace www\examplenamespace\cl\service;
/**
 * @generated The structure of this interface is generated by CloudKing
 * Interface IExampleHelloService
 */
interface IExampleHelloService {
	/**
	 * Example of function
	 *
	 * @param mixed $param
	 *
	 * @return mixed
	 */
	public function hello(&$param);
} // end class 
 